---
title: "Day 1: Dipping Your Toes into Data Visualization with R"
author: "Emi Tanaka"
date: "11th November 2020"
---

## Slides

We recommend that you open the html slides <i class="fas fa-link"></i> with [Google Chrome web browser](https://www.google.com/intl/en_au/chrome/). 

0. Getting started [<i class="fas fa-link"></i>](slides/day1-session0.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session0.pdf)
1. Grammar of Graphics [<i class="fas fa-link"></i>](slides/day1-session1.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session1.pdf)
2. Multiple layers, facetting and tidying your data [<i class="fas fa-link"></i>](slides/day1-session2.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session2.pdf)
3. Scales and color [<i class="fas fa-link"></i>](slides/day1-session3.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session3.pdf)
4. Publication-ready plots [<i class="fas fa-link"></i>](slides/day1-session4.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session4.pdf)

## Schedule

Time | Activity 
:----|:---
1.00-1.30 | Registration + Installation Help
1.30-2.00 | **Lesson 1:** Getting started with grammar of graphics
2.00-2.15 |  *Break out session*
2.15-2.45 | **Lesson 2:**  Multiple layers, facetting and tidying your data
2.45-3.00 | *Break out session*
3.00-3.30 | *Coffee Break*
3.30-4.00 | **Lesson 3:** Scales and color
4.00-4.15 | *Break out session*
4.15-4.45 | **Lesson 4:** Publication-ready plots
4.45-5.00 | *Break out session* 


## Exercises

Before getting started, you will need to install the following R-packages:

```r
```{r, echo = FALSE, results='asis'}
pkgs <- readLines("install-pkgs-day1.txt")
pkgsq <- paste0("'", pkgs, "'")
glue::glue("
  install.packages(c( {paste0(pkgsq, collapse=',\\n\\t\\t\\t\\t\\t')}))
  ")
```
```

1. Mastering the `geom`s <a class="tag" href="exercises/day1-exercise-01.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-01.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-01-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-01-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>

2. Taming data and multiples <a class="tag" href="exercises/day1-exercise-02.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-02.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-02-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-02-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>


3. Playing with scales and color <a class="tag" href="exercises/day1-exercise-03.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-03.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-03-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-03-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>

4. Jazzy plots <a class="tag" href="exercises/day1-exercise-04.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-04.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-04-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-04-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>

